name: hn_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  font_awesome_flutter: ^8.4.0
  rxdart: ^0.21.0
  http: ^0.12.0+1
  built_collection: ^4.1.0
  built_value: ^6.3.1
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  url_launcher: ^5.0.1


dev_dependencies:
  build_runner: ^1.0.0
  built_value_generator: ^6.3.1
  test: ^1.5.3
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
